version: '3'

services:
  covid19_1:
    build: .
    ports:
      - "8003:8001"

  covid19_2:
    build: .
    ports:
      - "8004:8001"

  nginx:
    build: ./docker/nginx
    ports:
      - "8010:80"
    depends_on:
      - covid19_1
      - covid19_2
