name: Run Tests
on: [push]
jobs:
  Execute-Tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: python -m unittest
